/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthControllerCallbackParams,
  AuthControllerLoginParams,
  AuthMeResponseDto,
  CreateTaskDto,
  CreateUserDto,
  LoginRequestDto,
  ManagedUserDto,
  PaginatedTasksResponseDto,
  PaginatedUsersResponseDto,
  ProblemDetailsDto,
  SetUserStatusDto,
  TaskDto,
  TasksControllerFindAllParams,
  UpdateSelfUserDto,
  UpdateTaskDto,
  UpdateUserDto,
  UserControllerListParams
} from './models';

import { customFetch } from './custom-fetch';

export type healthControllerLiveResponse200 = {
  data: unknown
  status: 200
}

export type healthControllerLiveResponseSuccess = (healthControllerLiveResponse200) & {
  headers: Headers;
};
;

export type healthControllerLiveResponse = (healthControllerLiveResponseSuccess)

export const getHealthControllerLiveUrl = () => {




  return `/health/live`
}

/**
 * @summary Liveness health check
 */
export const healthControllerLive = async ( options?: Parameters<typeof customFetch>[1]): Promise<healthControllerLiveResponse> => {

  return customFetch<healthControllerLiveResponse>(getHealthControllerLiveUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type healthControllerReadyResponse200 = {
  data: unknown
  status: 200
}

export type healthControllerReadyResponse503 = {
  data: ProblemDetailsDto
  status: 503
}

export type healthControllerReadyResponseSuccess = (healthControllerReadyResponse200) & {
  headers: Headers;
};
export type healthControllerReadyResponseError = (healthControllerReadyResponse503) & {
  headers: Headers;
};

export type healthControllerReadyResponse = (healthControllerReadyResponseSuccess | healthControllerReadyResponseError)

export const getHealthControllerReadyUrl = () => {




  return `/health/ready`
}

/**
 * @summary Readiness health check incluindo conectividade com banco
 */
export const healthControllerReady = async ( options?: Parameters<typeof customFetch>[1]): Promise<healthControllerReadyResponse> => {

  return customFetch<healthControllerReadyResponse>(getHealthControllerReadyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type authControllerDirectLoginResponse200 = {
  data: AuthMeResponseDto
  status: 200
}

export type authControllerDirectLoginResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type authControllerDirectLoginResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type authControllerDirectLoginResponseSuccess = (authControllerDirectLoginResponse200) & {
  headers: Headers;
};
export type authControllerDirectLoginResponseError = (authControllerDirectLoginResponse400 | authControllerDirectLoginResponse401) & {
  headers: Headers;
};

export type authControllerDirectLoginResponse = (authControllerDirectLoginResponseSuccess | authControllerDirectLoginResponseError)

export const getAuthControllerDirectLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Autenticar com credenciais de forma direta (inicia sessão segura)
 */
export const authControllerDirectLogin = async (loginRequestDto: LoginRequestDto, options?: Parameters<typeof customFetch>[1]): Promise<authControllerDirectLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<authControllerDirectLoginResponse>(getAuthControllerDirectLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequestDto)
  }
);}



export type authControllerLoginResponse302 = {
  data: void
  status: 302
}

;
export type authControllerLoginResponseError = (authControllerLoginResponse302) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseError)

export const getAuthControllerLoginUrl = (params?: AuthControllerLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/login?${stringifiedParams}` : `/api/v1/auth/login`
}

/**
 * @summary Iniciar autenticação OIDC (redireciona para o provedor)
 */
export const authControllerLogin = async (params?: AuthControllerLoginParams, options?: Parameters<typeof customFetch>[1]): Promise<authControllerLoginResponse> => {

  return customFetch<authControllerLoginResponse>(getAuthControllerLoginUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type authControllerCallbackResponse303 = {
  data: void
  status: 303
}

export type authControllerCallbackResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

;
export type authControllerCallbackResponseError = (authControllerCallbackResponse303 | authControllerCallbackResponse400) & {
  headers: Headers;
};

export type authControllerCallbackResponse = (authControllerCallbackResponseError)

export const getAuthControllerCallbackUrl = (params?: AuthControllerCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/callback?${stringifiedParams}` : `/api/v1/auth/callback`
}

/**
 * @summary Receber callback OIDC e criar sessão local em cookie
 */
export const authControllerCallback = async (params?: AuthControllerCallbackParams, options?: Parameters<typeof customFetch>[1]): Promise<authControllerCallbackResponse> => {

  return customFetch<authControllerCallbackResponse>(getAuthControllerCallbackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type authControllerMeResponse200 = {
  data: AuthMeResponseDto
  status: 200
}

export type authControllerMeResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type authControllerMeResponseSuccess = (authControllerMeResponse200) & {
  headers: Headers;
};
export type authControllerMeResponseError = (authControllerMeResponse401) & {
  headers: Headers;
};

export type authControllerMeResponse = (authControllerMeResponseSuccess | authControllerMeResponseError)

export const getAuthControllerMeUrl = () => {




  return `/api/v1/auth/me`
}

/**
 * @summary Consultar perfil do usuário autenticado atual
 */
export const authControllerMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerMeResponse> => {

  return customFetch<authControllerMeResponse>(getAuthControllerMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type authControllerLogoutResponse303 = {
  data: void
  status: 303
}

export type authControllerLogoutResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type authControllerLogoutResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

;
export type authControllerLogoutResponseError = (authControllerLogoutResponse303 | authControllerLogoutResponse401 | authControllerLogoutResponse403) & {
  headers: Headers;
};

export type authControllerLogoutResponse = (authControllerLogoutResponseError)

export const getAuthControllerLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * @summary Encerrar sessão atual e executar logout federado
 */
export const authControllerLogout = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerLogoutResponse> => {

  return customFetch<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export type authControllerLogoutAllResponse204 = {
  data: void
  status: 204
}

export type authControllerLogoutAllResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type authControllerLogoutAllResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type authControllerLogoutAllResponseSuccess = (authControllerLogoutAllResponse204) & {
  headers: Headers;
};
export type authControllerLogoutAllResponseError = (authControllerLogoutAllResponse401 | authControllerLogoutAllResponse403) & {
  headers: Headers;
};

export type authControllerLogoutAllResponse = (authControllerLogoutAllResponseSuccess | authControllerLogoutAllResponseError)

export const getAuthControllerLogoutAllUrl = () => {




  return `/api/v1/auth/logout-all`
}

/**
 * @summary Encerrar todas as sessões locais ativas do usuário
 */
export const authControllerLogoutAll = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerLogoutAllResponse> => {

  return customFetch<authControllerLogoutAllResponse>(getAuthControllerLogoutAllUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export type authControllerAccountResponse302 = {
  data: void
  status: 302
}

;
export type authControllerAccountResponseError = (authControllerAccountResponse302) & {
  headers: Headers;
};

export type authControllerAccountResponse = (authControllerAccountResponseError)

export const getAuthControllerAccountUrl = () => {




  return `/api/v1/auth/account`
}

/**
 * @summary Redirecionar para gerenciamento central de conta
 */
export const authControllerAccount = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerAccountResponse> => {

  return customFetch<authControllerAccountResponse>(getAuthControllerAccountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type adminAccessControllerCheckResponse200 = {
  data: void
  status: 200
}

export type adminAccessControllerCheckResponseSuccess = (adminAccessControllerCheckResponse200) & {
  headers: Headers;
};
;

export type adminAccessControllerCheckResponse = (adminAccessControllerCheckResponseSuccess)

export const getAdminAccessControllerCheckUrl = () => {




  return `/api/v1/admin/access-check`
}

export const adminAccessControllerCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<adminAccessControllerCheckResponse> => {

  return customFetch<adminAccessControllerCheckResponse>(getAdminAccessControllerCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type userControllerListResponse200 = {
  data: PaginatedUsersResponseDto
  status: 200
}

export type userControllerListResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerListResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type userControllerListResponseSuccess = (userControllerListResponse200) & {
  headers: Headers;
};
export type userControllerListResponseError = (userControllerListResponse401 | userControllerListResponse403) & {
  headers: Headers;
};

export type userControllerListResponse = (userControllerListResponseSuccess | userControllerListResponseError)

export const getUserControllerListUrl = (params?: UserControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/users?${stringifiedParams}` : `/api/v1/users`
}

/**
 * @summary Listar usuários com paginação e busca (ADMIN)
 */
export const userControllerList = async (params?: UserControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<userControllerListResponse> => {

  return customFetch<userControllerListResponse>(getUserControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type userControllerCreateResponse201 = {
  data: ManagedUserDto
  status: 201
}

export type userControllerCreateResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type userControllerCreateResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerCreateResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type userControllerCreateResponse409 = {
  data: ProblemDetailsDto
  status: 409
}

export type userControllerCreateResponseSuccess = (userControllerCreateResponse201) & {
  headers: Headers;
};
export type userControllerCreateResponseError = (userControllerCreateResponse400 | userControllerCreateResponse401 | userControllerCreateResponse403 | userControllerCreateResponse409) & {
  headers: Headers;
};

export type userControllerCreateResponse = (userControllerCreateResponseSuccess | userControllerCreateResponseError)

export const getUserControllerCreateUrl = () => {




  return `/api/v1/users`
}

/**
 * @summary Criar usuário e provisionar perfil (ADMIN)
 */
export const userControllerCreate = async (createUserDto: CreateUserDto, options?: Parameters<typeof customFetch>[1]): Promise<userControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<userControllerCreateResponse>(getUserControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createUserDto)
  }
);}



export type userControllerUpdateMeResponse200 = {
  data: ManagedUserDto
  status: 200
}

export type userControllerUpdateMeResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type userControllerUpdateMeResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerUpdateMeResponseSuccess = (userControllerUpdateMeResponse200) & {
  headers: Headers;
};
export type userControllerUpdateMeResponseError = (userControllerUpdateMeResponse400 | userControllerUpdateMeResponse401) & {
  headers: Headers;
};

export type userControllerUpdateMeResponse = (userControllerUpdateMeResponseSuccess | userControllerUpdateMeResponseError)

export const getUserControllerUpdateMeUrl = () => {




  return `/api/v1/users/me`
}

/**
 * @summary Atualizar dados permitidos do próprio perfil
 */
export const userControllerUpdateMe = async (updateSelfUserDto: UpdateSelfUserDto, options?: Parameters<typeof customFetch>[1]): Promise<userControllerUpdateMeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<userControllerUpdateMeResponse>(getUserControllerUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateSelfUserDto)
  }
);}



export type userControllerGetByIdResponse200 = {
  data: ManagedUserDto
  status: 200
}

export type userControllerGetByIdResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerGetByIdResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type userControllerGetByIdResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type userControllerGetByIdResponseSuccess = (userControllerGetByIdResponse200) & {
  headers: Headers;
};
export type userControllerGetByIdResponseError = (userControllerGetByIdResponse401 | userControllerGetByIdResponse403 | userControllerGetByIdResponse404) & {
  headers: Headers;
};

export type userControllerGetByIdResponse = (userControllerGetByIdResponseSuccess | userControllerGetByIdResponseError)

export const getUserControllerGetByIdUrl = (id: string,) => {




  return `/api/v1/users/${id}`
}

/**
 * @summary Obter detalhes de um usuário por ID (ADMIN)
 */
export const userControllerGetById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<userControllerGetByIdResponse> => {

  return customFetch<userControllerGetByIdResponse>(getUserControllerGetByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type userControllerUpdateResponse200 = {
  data: ManagedUserDto
  status: 200
}

export type userControllerUpdateResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type userControllerUpdateResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerUpdateResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type userControllerUpdateResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type userControllerUpdateResponseSuccess = (userControllerUpdateResponse200) & {
  headers: Headers;
};
export type userControllerUpdateResponseError = (userControllerUpdateResponse400 | userControllerUpdateResponse401 | userControllerUpdateResponse403 | userControllerUpdateResponse404) & {
  headers: Headers;
};

export type userControllerUpdateResponse = (userControllerUpdateResponseSuccess | userControllerUpdateResponseError)

export const getUserControllerUpdateUrl = (id: string,) => {




  return `/api/v1/users/${id}`
}

/**
 * @summary Atualizar usuário e sincronizar perfil (ADMIN)
 */
export const userControllerUpdate = async (id: string,
    updateUserDto: UpdateUserDto, options?: Parameters<typeof customFetch>[1]): Promise<userControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<userControllerUpdateResponse>(getUserControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateUserDto)
  }
);}



export type userControllerSetStatusResponse200 = {
  data: ManagedUserDto
  status: 200
}

export type userControllerSetStatusResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type userControllerSetStatusResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type userControllerSetStatusResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type userControllerSetStatusResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type userControllerSetStatusResponseSuccess = (userControllerSetStatusResponse200) & {
  headers: Headers;
};
export type userControllerSetStatusResponseError = (userControllerSetStatusResponse400 | userControllerSetStatusResponse401 | userControllerSetStatusResponse403 | userControllerSetStatusResponse404) & {
  headers: Headers;
};

export type userControllerSetStatusResponse = (userControllerSetStatusResponseSuccess | userControllerSetStatusResponseError)

export const getUserControllerSetStatusUrl = (id: string,) => {




  return `/api/v1/users/${id}/status`
}

/**
 * @summary Ativar ou desativar usuário (ADMIN)
 */
export const userControllerSetStatus = async (id: string,
    setUserStatusDto: SetUserStatusDto, options?: Parameters<typeof customFetch>[1]): Promise<userControllerSetStatusResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<userControllerSetStatusResponse>(getUserControllerSetStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setUserStatusDto)
  }
);}



export type tasksControllerCreateResponse201 = {
  data: TaskDto
  status: 201
}

export type tasksControllerCreateResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type tasksControllerCreateResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type tasksControllerCreateResponseSuccess = (tasksControllerCreateResponse201) & {
  headers: Headers;
};
export type tasksControllerCreateResponseError = (tasksControllerCreateResponse400 | tasksControllerCreateResponse401) & {
  headers: Headers;
};

export type tasksControllerCreateResponse = (tasksControllerCreateResponseSuccess | tasksControllerCreateResponseError)

export const getTasksControllerCreateUrl = () => {




  return `/api/v1/tasks`
}

/**
 * Cria uma nova tarefa associando-a ao usuário autenticado como proprietário.
 * @summary Criar nova tarefa
 */
export const tasksControllerCreate = async (createTaskDto: CreateTaskDto, options?: Parameters<typeof customFetch>[1]): Promise<tasksControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<tasksControllerCreateResponse>(getTasksControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTaskDto)
  }
);}



export type tasksControllerFindAllResponse200 = {
  data: PaginatedTasksResponseDto
  status: 200
}

export type tasksControllerFindAllResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type tasksControllerFindAllResponseSuccess = (tasksControllerFindAllResponse200) & {
  headers: Headers;
};
export type tasksControllerFindAllResponseError = (tasksControllerFindAllResponse401) & {
  headers: Headers;
};

export type tasksControllerFindAllResponse = (tasksControllerFindAllResponseSuccess | tasksControllerFindAllResponseError)

export const getTasksControllerFindAllUrl = (params?: TasksControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/tasks?${stringifiedParams}` : `/api/v1/tasks`
}

/**
 * Lista tarefas com paginação, busca por texto, filtro por status/prioridade e ordenação.
 * @summary Listar tarefas paginadas
 */
export const tasksControllerFindAll = async (params?: TasksControllerFindAllParams, options?: Parameters<typeof customFetch>[1]): Promise<tasksControllerFindAllResponse> => {

  return customFetch<tasksControllerFindAllResponse>(getTasksControllerFindAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type tasksControllerFindByIdResponse200 = {
  data: TaskDto
  status: 200
}

export type tasksControllerFindByIdResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type tasksControllerFindByIdResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type tasksControllerFindByIdResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type tasksControllerFindByIdResponseSuccess = (tasksControllerFindByIdResponse200) & {
  headers: Headers;
};
export type tasksControllerFindByIdResponseError = (tasksControllerFindByIdResponse401 | tasksControllerFindByIdResponse403 | tasksControllerFindByIdResponse404) & {
  headers: Headers;
};

export type tasksControllerFindByIdResponse = (tasksControllerFindByIdResponseSuccess | tasksControllerFindByIdResponseError)

export const getTasksControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * Retorna os detalhes de uma tarefa específica pertencente ao usuário (ou qualquer tarefa para ADMIN).
 * @summary Obter detalhes de uma tarefa
 */
export const tasksControllerFindById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<tasksControllerFindByIdResponse> => {

  return customFetch<tasksControllerFindByIdResponse>(getTasksControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type tasksControllerUpdateResponse200 = {
  data: TaskDto
  status: 200
}

export type tasksControllerUpdateResponse400 = {
  data: ProblemDetailsDto
  status: 400
}

export type tasksControllerUpdateResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type tasksControllerUpdateResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type tasksControllerUpdateResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type tasksControllerUpdateResponseSuccess = (tasksControllerUpdateResponse200) & {
  headers: Headers;
};
export type tasksControllerUpdateResponseError = (tasksControllerUpdateResponse400 | tasksControllerUpdateResponse401 | tasksControllerUpdateResponse403 | tasksControllerUpdateResponse404) & {
  headers: Headers;
};

export type tasksControllerUpdateResponse = (tasksControllerUpdateResponseSuccess | tasksControllerUpdateResponseError)

export const getTasksControllerUpdateUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * Atualiza os dados ou status de uma tarefa respeitando as regras de negócio e ownership.
 * @summary Atualizar tarefa
 */
export const tasksControllerUpdate = async (id: string,
    updateTaskDto: UpdateTaskDto, options?: Parameters<typeof customFetch>[1]): Promise<tasksControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<tasksControllerUpdateResponse>(getTasksControllerUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTaskDto)
  }
);}



export type tasksControllerRemoveResponse204 = {
  data: void
  status: 204
}

export type tasksControllerRemoveResponse401 = {
  data: ProblemDetailsDto
  status: 401
}

export type tasksControllerRemoveResponse403 = {
  data: ProblemDetailsDto
  status: 403
}

export type tasksControllerRemoveResponse404 = {
  data: ProblemDetailsDto
  status: 404
}

export type tasksControllerRemoveResponseSuccess = (tasksControllerRemoveResponse204) & {
  headers: Headers;
};
export type tasksControllerRemoveResponseError = (tasksControllerRemoveResponse401 | tasksControllerRemoveResponse403 | tasksControllerRemoveResponse404) & {
  headers: Headers;
};

export type tasksControllerRemoveResponse = (tasksControllerRemoveResponseSuccess | tasksControllerRemoveResponseError)

export const getTasksControllerRemoveUrl = (id: string,) => {




  return `/api/v1/tasks/${id}`
}

/**
 * Realiza a remoção lógica (soft delete) da tarefa.
 * @summary Excluir tarefa (remoção lógica)
 */
export const tasksControllerRemove = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<tasksControllerRemoveResponse> => {

  return customFetch<tasksControllerRemoveResponse>(getTasksControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



