/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoria da tarefa
 */
export type CreateTaskDtoCategory = typeof CreateTaskDtoCategory[keyof typeof CreateTaskDtoCategory];


export const CreateTaskDtoCategory = {
  WORK: 'WORK',
  STUDY: 'STUDY',
  PERSONAL: 'PERSONAL',
  HEALTH: 'HEALTH',
  OTHER: 'OTHER',
} as const;
