/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTaskDtoCategory } from './createTaskDtoCategory';
import type { CreateTaskDtoPriority } from './createTaskDtoPriority';

export interface CreateTaskDto {
  /**
     * Título da tarefa
     * @minLength 3
     * @maxLength 150
     */
  title: string;
  /**
     * Descrição detalhada da tarefa
     * @maxLength 1000
     */
  description?: string;
  /** Prioridade da tarefa */
  priority?: CreateTaskDtoPriority;
  /** Categoria da tarefa */
  category?: CreateTaskDtoCategory;
  /** Data de entrega limite (ISO 8601) */
  dueDate?: string;
}
