/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { TasksControllerFindAllCategory } from './tasksControllerFindAllCategory';
import type { TasksControllerFindAllPriority } from './tasksControllerFindAllPriority';
import type { TasksControllerFindAllSortBy } from './tasksControllerFindAllSortBy';
import type { TasksControllerFindAllSortOrder } from './tasksControllerFindAllSortOrder';
import type { TasksControllerFindAllStatus } from './tasksControllerFindAllStatus';

export type TasksControllerFindAllParams = {
/**
 * Número da página
 * @minimum 1
 */
page?: number;
/**
 * Itens por página
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
/**
 * Termo de busca
 * @maxLength 120
 */
search?: string;
/**
 * Filtro por status
 */
status?: TasksControllerFindAllStatus;
/**
 * Filtro por prioridade
 */
priority?: TasksControllerFindAllPriority;
/**
 * Filtro por categoria
 */
category?: TasksControllerFindAllCategory;
/**
 * Campo de ordenação
 */
sortBy?: TasksControllerFindAllSortBy;
/**
 * Direção da ordenação
 */
sortOrder?: TasksControllerFindAllSortOrder;
};
