/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTaskDtoCategory } from './updateTaskDtoCategory';
import type { UpdateTaskDtoPriority } from './updateTaskDtoPriority';
import type { UpdateTaskDtoStatus } from './updateTaskDtoStatus';

export interface UpdateTaskDto {
  /**
     * Título da tarefa
     * @minLength 3
     * @maxLength 150
     */
  title?: string;
  /**
     * Descrição detalhada da tarefa
     * @maxLength 1000
     */
  description?: string;
  /** Status atual da tarefa */
  status?: UpdateTaskDtoStatus;
  /** Prioridade da tarefa */
  priority?: UpdateTaskDtoPriority;
  /** Categoria da tarefa */
  category?: UpdateTaskDtoCategory;
  /** Data de entrega limite (ISO 8601) */
  dueDate?: string;
}
